name: Test HTML & CSS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push static site image
      run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t ${{ secrets.DOCKER_USERNAME }}/static-site:latest \
            .
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install linters
      run: |
        npm install -g htmlhint stylelint stylelint-config-standard

    - name: test HTML
      run: htmlhint index.html

    - name: Create stylelint config
      run: |
        cat <<EOF > .stylelintrc.json
        {
          "extends": "stylelint-config-standard"
        }
        EOF

    - name: test CSS
      run: stylelint "style.css"