name: Test HTML & CSS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install linters
      run: |
        npm install -g htmlhint stylelint stylelint-config-standard

    - name: Lint HTML
      run: htmlhint index.html

    - name: Create stylelint config
      run: |
        cat <<EOF > .stylelintrc.json
        {
          "extends": "stylelint-config-standard"
        }
        EOF

    - name: Lint CSS
      run: stylelint "style.css"